### ISSUE TITLE
Move the plugin to "More Tools" or "Data" menu

### ISSUE THREAD

**Issue by Klumbumbus** [JOSM/turnlanes-tagging#21]
Currently it is placed in the "Edit" menu. Other plugins put their entries usually in the  "More Tools" or "Data" menu.
Examples of entries in these menus:
![data](https://cloud.githubusercontent.com/assets/7115609/16017520/9880a51e-31a0-11e6-9b68-5384383895c9.png)
![moretools](https://cloud.githubusercontent.com/assets/7115609/16017521/98863286-31a0-11e6-882b-6e8d690e7445.png)

BTW this is a really great plugin. Thanks!

**Comment by Rub21** [comment]
@Klumbumbus , Thanks for your feedbacks,  I decided to put the plugin entry in `Edit`, because i found other plugin called [JOSM Tag Editor Plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/TagEditor)  on `Edit` menu.  what do you think?
However `Data` menu is a good option too.

![turnlanes91-21](https://cloud.githubusercontent.com/assets/1152236/16022582/2d57053e-317e-11e6-9539-d15cdeef655a.gif)

**Comment by Rub21** [comment]
done! the plugin is in `data` menu
