### ISSUE TITLE
add reverse | slight_left |   merge_to_right |  merge_to_left |     slight_right 

### ISSUE THREAD

**Issue by Rub21** [JOSM/turnlanes-tagging#4]

**Comment by Rub21** [comment]
cc @Andygol

**Comment by Andygol** [comment]
@Rub21 
In order not to clutter the interface I suggest a three(four)-positional switches for this

◻️◻️◻️ - initial `blank` position
⬅️◻️◻️ - `left` - 1st position
↖️◻️◻️ - `slight_left` - 2nd position
↗️◻️◻️ - `merge_to_right` - 3rd position

Need to apply this only for leftmost lane and accordingly `right*` clause for the rightmost lane

Instead of emoji arrows there would be great to use road signs and combine them in the editor dialog to a such plate ![](https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/5.15.1_Russian_road_sign.svg/80px-5.15.1_Russian_road_sign.svg.png)

| sign | tag | link |
| --- | --- | --- |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/5.8_Russian_road_sign.svg/40px-5.8_Russian_road_sign.svg.png) | `reverse` | https://commons.wikimedia.org/wiki/File:5.8_Russian_road_sign.svg |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/5.15.2_A_Russian_road_sign.svg/40px-5.15.2_A_Russian_road_sign.svg.png) | `through` | https://commons.wikimedia.org/wiki/File:5.15.2_A_Russian_road_sign.svg |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/5.15.2_C_Russian_road_sign.svg/40px-5.15.2_C_Russian_road_sign.svg.png) | `right`\`left` | https://commons.wikimedia.org/wiki/File:5.15.2_C_Russian_road_sign.svg |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/5.15.2_D_Russian_road_sign.svg/40px-5.15.2_D_Russian_road_sign.svg.png) | `slight_right`\`slight_left` | https://commons.wikimedia.org/wiki/File:5.15.2_D_Russian_road_sign.svg |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/5.15.6_Russian_road_sign.svg/40px-5.15.6_Russian_road_sign.svg.png) ![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/5.15.5_Russian_road_sign.svg/40px-5.15.5_Russian_road_sign.svg.png) | `merge_to_right`\`merge_to_left` | https://commons.wikimedia.org/wiki/File:5.15.6_Russian_road_sign.svg https://commons.wikimedia.org/wiki/File:5.15.5_Russian_road_sign.svg |
| ![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/5.15.4_A_Russian_road_sign.svg/40px-5.15.4_A_Russian_road_sign.svg.png)![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/5.15.3_A_Russian_road_sign.svg/40px-5.15.3_A_Russian_road_sign.svg.png) |  | https://commons.wikimedia.org/wiki/File:5.15.4_A_Russian_road_sign.svg https://commons.wikimedia.org/wiki/File:5.15.3_A_Russian_road_sign.svg |

**Comment by Andygol** [comment]
Or another variant 

for the 1st (last) lane

| --- | --- | --- |
| --- | --- | --- |
| ↖️ |  | ↗️ |
| ⬅️ | ⬆️ | ➡️ |
| ↗️ |  | ↖️ |

👇 for lanes in a middle position

| --- | --- | --- |
| --- | --- | --- |
| ↖️ |  | ↗️ |
| ⬅️ | ⬆️ | ➡️ |

**Comment by Rub21** [comment]
done here!
