### ISSUE TITLE
Error en el estilo para paises con el tránsito por laizquiera

### ISSUE THREAD

**Issue by RichRico** [JOSM/turnlanes-tagging#48]
@Rub21 @Andygol 

Segun esta imagen, en el plugin de turn lanes, el orden en que se pone los tags es correcto, pero en los estilos muestra al al revés la señalización, deberia de mostrar tal como se ingresa en el plugin

![turnlanes](https://cloud.githubusercontent.com/assets/8484029/16690341/06f4762e-44ed-11e6-9b57-c65851bc75d5.png)

**Comment by Andygol** [comment]
There is need to fix mappaint style in JOSM. So, need post issue in https://josm.openstreetmap.de/report
/cc @RichRico

**Comment by Klumbumbus** [comment]
what is the id of this way?

**Comment by RichRico** [comment]
Url: https://www.openstreetmap.org/way/115872020

**Comment by Klumbumbus** [comment]
The [wiki](http://wiki.openstreetmap.org/wiki/Lanes) says "...in left-to-right order as viewed in the respective driving direction of those lanes."
So the way is tagged wrong, it should be turn:lanes:forward=through|right. Then the mappaint is correct (same as aerial photo) but the plugin (version 1467927825) displays it different.
![turnlanestagging-japan](https://cloud.githubusercontent.com/assets/7115609/16696236/5f0779ea-4544-11e6-89ba-6eaa38d9c30f.png)

**Comment by Andygol** [comment]
@Klumbumbus 
I mean that we could count number of lanes **from** the _center_ line **to** the _outmost_ lane
- from left-to-right for right-hand traffic
- from right-to-left for right-hand traffic

In this case we have a holistic approach, rather than as now described in the Wiki.

Now (according to wiki) we count lanes for the _right-hand_ traffic from the center line to the outmost lane but for left-hand traffic from the outmost lane to the center line. There is should be only one option for lanes counting for any right- or left-hand traffic -- from the center line of the road.

UPD
Or maybe I'm wrong 😕

**Comment by Klumbumbus** [comment]
Both is possible. It's a question of definition. The current definition is written in the wiki (left to right). All the already tagged lanes should follow this definition. You cannot simply change this definition because this would turn all the tagged lanes in left-hand traffic areas into wrong tagged ways.

Also this depends on the point of view. With the current definition we always count from left to right while with your definition we count in right-hand traffic from left to right and in left-hand traffic from right to left. So from this point of view the current definiton is more holistic.

**Comment by Andygol** [comment]
> Both is possible. It's a question of definition. … You cannot simply change this definition because this would turn all the tagged lanes in left-hand traffic areas into wrong tagged ways.

I agreed with you ☝️ 

But I want to share my reflections.

Before I started working with turn:lanes tagging I always count lanes from the outmost side of the road. Since all members of the movement begin its movement from the outer side of the road, this lane is always called first lane regardless of the side of traffic. 

<img width="428" alt="java openstreetmap editor 2016-07-08 23-14-53" src="https://cloud.githubusercontent.com/assets/369696/16700352/394f8422-4562-11e6-9215-75b1b39d9fc4.png">

But when I began to study in more detail the wiki, I found out that the lanes counting going from left to right. Ok, I took it on the fact that we draw way in the middle of the **axial line** of the road, then we count (for right-hand traffic) lanes from the road line - from the **center** line.

And the fact, that we simply number the lanes from left to right, regardless of the traffic side, is confused me a bit.

**Comment by Rub21** [comment]
@Andygol @Klumbumbus @RichRico , I' ve fixed the error, can you take a look.

**For `left-hand` -> from outmost to the center**

![image](https://cloud.githubusercontent.com/assets/1152236/16748103/cfefa692-4787-11e6-9838-7be5d8862c76.png)
https://www.openstreetmap.org/way/154330573

**For the `right-hand` -> from the center line to the outmost**

![image](https://cloud.githubusercontent.com/assets/1152236/16748017/4e24618e-4787-11e6-94f2-4886d1c905f7.png)

https://www.openstreetmap.org/way/29059461

**Comment by Andygol** [comment]
@Rub21 
👍 As for me all works great

**Comment by Rub21** [comment]
@Andygol @Klumbumbus Thank you for you clarification, this is ready!

**Comment by Klumbumbus** [comment]
Looks fine now. Thanks.
