### ISSUE TITLE
Preset Turn Lanes Names

### ISSUE THREAD

**Issue by baditaflorin** [JOSM/turnlanes-tagging#50]
Now, it`s hard to understand based on the image whet each of them means, and you have to click each one to find out. The ability to add a name that could add as a description would help the users better remember what it`s the specific item about.

**Comment by Rub21** [comment]
@baditaflorin  Right now we have a list of `Preset Turn Lanes` , I am not sure how can we add a description of them because the description of this  is in the column `Turn lanes`, Could you give somo example to understand more the issues.
![image](https://cloud.githubusercontent.com/assets/1152236/17006145/57e88df2-4ea4-11e6-9555-bb21c5301ba3.png)

**Comment by samely** [comment]
Hey @baditaflorin I guess you're talking about the set of icons for every `turn:lanes`
![image](https://cloud.githubusercontent.com/assets/10425629/17410576/f1068462-5a39-11e6-8ca0-1116f3304296.png)

If you pass the mouse pointer over the icon you can see the name of the `turn:lanes`. See bellow.
![anim](https://cloud.githubusercontent.com/assets/10425629/17410676/5960f524-5a3a-11e6-8b14-4ca0fb566e8a.gif)

However, if I'm wrong and you still have a feedback for this, please re-open the ticket.
